class_name Strings
extends RefCounted
## Todos los textos de la terminal, en español. Nada de literales en las escenas.

const BOOT_LOADING := "Preparando tu partida"
const MENU_TITLE_PREFIX := "Elige tu "
const MENU_TITLE_WORD := "juego"
const POWERED_BY := "powered by"
const IN_PROGRESS := "EN PROCESO"
const PRESS_TO_PLAY := "PULSA ESPACIO"
const DURATION := "%d s"
const HELP_CHOOSE := "Elegir"
const HELP_PLAY := "Jugar"
const KEY_LEFT_RIGHT := "← →"
const KEY_SPACE := "ESPACIO"
const NOT_AVAILABLE := "Este juego llega pronto"
const GAME_COMING := "%s se activa en la siguiente fase"
const OFFLINE := "Sin conexión · usando la última marca guardada"

# Partida
const COUNT_GO := "¡YA!"
const HUD_SCORE := "PUNTOS"
const HUD_TIME := "TIEMPO"
const HUD_LIVES := "VIDAS"
const END_TIME := "Se acabó el tiempo"
const END_LIVES := "Sin vidas"
const END_TITLE := "FIN DE PARTIDA"
const ABANDON_TITLE := "¿Abandonar la partida?"
const ABANDON_BODY := "Perderás tu puntaje. La partida se cierra sola en %d s."
const ABANDON_KEEP := "Seguir jugando"
const ABANDON_QUIT := "Abandonar"

# Resultado
const RESULT_SCORE := "TU PUNTAJE"
const RESULT_RECORD := "¡NUEVO RÉCORD!"
const RESULT_BEST := "Mejor resultado: %d"
const RESULT_QR_SOON := "Aquí aparecerá tu recompensa"
const RESULT_QR_NOTE := "Podrás escanearlo con Kairos para sumar tus puntos."
const RESULT_AGAIN := "Jugar otra vez"
const RESULT_MENU := "Volver al menú"

# Serpiente Golosa
const SNAKE_CRASH := "¡CHOQUE!"

# Memory Rush
const MEMORY_TITLE := "MEMORY RUSH"
const MEMORY_WATCH := "OBSERVA LA SECUENCIA"
const MEMORY_REPEAT := "REPITE LA SECUENCIA CON LAS FLECHAS"
const MEMORY_CORRECT := "¡SECUENCIA CORRECTA!"
const MEMORY_TRY_AGAIN := "INTENTA DE NUEVO"
const MEMORY_MISTAKE := "¡SECUENCIA INCORRECTA!"
const MEMORY_ROUND := "RONDA %d"

# Meta de QR
const HUD_GOAL := "META DE RECOMPENSA · %d"
const HUD_GOAL_DONE := "¡RECOMPENSA GANADA!"
const GOAL_FLOAT := "¡RECOMPENSA GANADA!"
const DURATION_GOAL := "%d s · RECOMPENSA %d"

# Marcador
const KEY_UP := "↑"
const HELP_SCOREBOARD := "Marcador"
const SCOREBOARD_TITLE := "MARCADOR"
const SCOREBOARD_EMPTY := "---"
const SCOREBOARD_YOU := "TÚ"
const SCOREBOARD_BACK := "Volver"
const SCOREBOARD_SWITCH := "Cambiar de juego"
const ENTRY_TITLE := "¡ENTRASTE AL MARCADOR!"
const ENTRY_RANK := "PUESTO #%d"
const ENTRY_HINT := "Elige tus %d iniciales"
const ENTRY_DONE := "LISTO"
const ENTRY_KEYS_CHANGE := "Cambiar letra"
const ENTRY_KEYS_MOVE := "Mover"
const ENTRY_KEYS_OK := "Confirmar"
const ENTRY_BLOCKED := "Esas iniciales no están permitidas"
const ENTRY_AUTOSAVE := "Se guarda solo en %d s"
const RANK_CHIP := "PUESTO #%d EN EL MARCADOR"

# Resultado con QR
const RESULT_SCOREBOARD := "Marcador"
const QR_SCAN := "Abre Kairos en tu teléfono y escanea este código"
const QR_VALID := "VÁLIDO POR"
const QR_EXPIRED_TITLE := "CÓDIGO VENCIDO"
const QR_EXPIRED_NOTE := "Juega otra vez y llega a la meta para girar la ruleta de nuevo."
const GOAL_TITLE := "AÚN NO LLEGAS A LA META"
const GOAL_NOTE := "Te faltaron %d puntos para ganar tu recompensa."
const GOAL_TARGET := "META %d"
const GOAL_TIP := "Alcanza la meta en una sola partida y llévate tus puntos."
const QR_PROBLEM_TITLE := "ESTA MÁQUINA NO PUEDE ENTREGAR RECOMPENSAS"
const QR_PROBLEM_CONFIG := "Falta configurar la sucursal y la máquina."
const QR_PROBLEM_KEY := "Falta la llave de esta máquina."
const QR_PROBLEM_SIGN := "No se pudo firmar el código. Avisa al personal."

# Vinculación con el negocio
const LINK_TITLE := "VINCULA ESTA MÁQUINA"
const LINK_SUBTITLE := "Inicia sesión con tu negocio. Solo el administrador puede vincular una máquina."
const LINK_ALREADY := "Esta máquina ya está vinculada a %s. Si la vinculas de nuevo se crea una máquina nueva; revoca la anterior en el panel."
const LINK_SLUG := "Identificador del negocio"
const LINK_SLUG_HINT := "Ejemplo: cafeteria-aurora"
const LINK_EMAIL := "Correo"
const LINK_PASSWORD := "Contraseña"
const LINK_CONTINUE := "Continuar"
const LINK_CONNECTING := "Conectando…"
const LINK_SERVER := "Servidor: %s"
const LINK_SKIP := "Omitir (solo desarrollo)"
const LINK_CANCEL := "Cancelar"
const LINK_STORE_TITLE := "ELIGE LA SUCURSAL"
const LINK_STORE_HINT := "Esta máquina quedará en la sucursal que elijas."
const LINK_MACHINE_NAME := "Nombre de la máquina"
const LINK_MACHINE_DEFAULT := "Arcade"
const LINK_DO := "Vincular esta máquina"
const LINK_LINKING := "Vinculando…"
const LINK_BACK := "Cambiar de cuenta"
const LINK_NO_STORES := "Este negocio no tiene sucursales activas. Créalas primero en el panel."
const LINK_DONE_TITLE := "¡MÁQUINA VINCULADA!"
const LINK_DONE_BODY := "%s · %s"
const LINK_DONE_START := "Empezar"
const LINK_REQUIRED := "Completa todos los campos."
const LINK_NETWORK := "No hay conexión con el servidor. Revisa internet e inténtalo de nuevo."
const LINK_BAD_LOGIN := "Negocio, correo o contraseña incorrectos."
const LINK_NOT_ADMIN := "Solo el administrador del negocio puede vincular una máquina."
const LINK_RATE := "Demasiados intentos. Espera unos minutos."
const LINK_KEY_FAILED := "No se pudo crear la llave de esta máquina."
const LINK_SAVE_FAILED := "No se pudo guardar la configuración en este equipo."
const LINK_GENERIC := "No se pudo completar. Inténtalo de nuevo."

# Ayuda
const HELP_BUTTON := "?"
const HELP_TITLE := "AYUDA"
const HELP_LABEL := "Ayuda"
const HELP_THIS_SCREEN := "ESTA PANTALLA"
const HELP_CLOSE := "Entendido"
const HELP_CLOSE_HINT := "Pulsa ESPACIO, ESC o H para cerrar"
const KEY_DOWN := "↓"
const KEY_HELP := "H"
const HELP_HOW_TO_PLAY := "CÓMO SE JUEGA · %s"

# Opciones de administrador
const ADMIN_TITLE := "OPCIONES DE ADMINISTRADOR"
const ADMIN_SESSION := "Sesión de %s"
const ADMIN_RELINK := "Vincular de nuevo (crea una máquina nueva)"
const ADMIN_QUIT := "Salir de la aplicación"
const ADMIN_BACK := "Volver al menú"

# Ruleta
const ROULETTE_TITLE := "¡LLEGASTE A LA META!"
const ROULETTE_SUBTITLE := "Gira la ruleta y descubre tu recompensa"
const ROULETTE_PRESS := "PULSA ESPACIO PARA GIRAR"
const ROULETTE_SPINNING := "GIRANDO…"
const ROULETTE_AUTO := "Gira sola en %d s"
const ROULETTE_WON := "¡GANASTE!"
const ROULETTE_CONTINUE := "Pulsa ESPACIO para ver tu código"
const RESULT_REWARD_LABEL := "TU RECOMPENSA"
const NO_REWARDS_TITLE := "SIN RECOMPENSAS POR AHORA"
const NO_REWARDS_NOTE := "Este negocio todavía no tiene recompensas disponibles. Avisa al personal."
